### ISSUE TITLE
Große Drohnen nicht mittig

### ISSUE THREAD

**Issue by MokkaGnom** [DronesTowerDefence/DTD#32]
Die "Moads" sind nicht mittig auf der Strecke.
![image](https://user-images.githubusercontent.com/100208616/212118298-d83d89db-147f-4d03-96df-ef1c2a978cab.png)

**Comment by kelp-byte** [comment]
Garnichts Gesendet von Mail für Windows Von: Rainer WinklerGesendet: Montag, 20. Februar 2023 02:21An: DronesTowerDefence/DTDCc: Tim; AssignBetreff: Re: [DronesTowerDefence/DTD] Große Drohnen nicht mittig (Issue #32) Assigned #32 to @kelp-byte.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were assigned.Message ID: ***@***.***>
